#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE ROOT

### CREATE DIRECTORIES
mkdir -p "$logdir" "$datadir" "$datadir/counters"
chown www-data:www-data "$logdir" "$datadir" "$datadir/counters"

### INSTALL THIS SYSTEM
chmod +x "$(dirname $0)/bin/"*
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R

### RENAME FETCH CGI
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
[ -e "/home/otaki/rnd" ] && rnd=$(cat /home/otaki/rnd ) # REMOVE ON RELEASE
mv "fetch" "fetch_$rnd.cgi"

### PULL ARTICLE REPO
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown www-data:www-data "$contentsdir" -R

### INITIALIZE
touch "$datadir/INIT"
chown www-data:www-data "$datadir/INIT"
sudo -u www-data CONTENT_LENGTH="" $appdir/fetch_$rnd.cgi

echo "call fetch_$rnd.cgi from Github"
